### ISSUE TITLE
Error when model isn't located in the root of 'app' dir

### ISSUE THREAD

**Issue by hassansin** [idealogica/lavanda#1]
Hi, 

Thanks for this nice package. I'm playing around with it and starting to like it. I'm having a problem when model classes are in `app/Models` directory. The `getModelClass()` function doesn't take care of model namespace properly. To avoid it, I'm defining the function in `bootstrap/autoload.php`. Is there any better way?

**Comment by idealogica** [comment]
Hi, 
model_ns config entry added to Lavanda config file in latest dev commit.
You can publish config:
php artisan vendor:publish --provider 'Idealogica\Lavanda\LavandaServiceProvider' --tag=config
and then change model_ns value.
Thank you for using Lavanda =)
